version: "3"
services:
  ui:
    build: ./src/ui
    ports:
      - "9003:80"
    restart: unless-stopped
  api:
    build:
      context: ./src/server
    volumes:
      - /mnt/web-hosting/igc-files:/igc-files
      - /var/log/glider-view:/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:gliderView=${CONNECTION_STRING}
    ports:
      - "9004:80"
    restart: unless-stopped
  igcd:
    build:
      context: ./src/igcd
    # command: -debug
    volumes:
      - type: bind
        source: ./src/igcd/conf.yml
        target: /igcd/conf.yml
        read_only: true
    restart: unless-stopped

