USE master
GO

CREATE LOGIN gliderViewer WITH PASSWORD = 'Passw0rd';

USE GliderViewer
GO

CREATE USER gliderViewer FOR LOGIN gliderViewer;

GRANT SELECT, INSERT, UPDATE ON schema::dbo TO gliderViewer;
GO

CREATE TABLE Glider (
	GliderId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	GliderGuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	TrackerId CHAR(6),
	Description VARCHAR(100),
	Registration CHAR(6),
	AddedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IsDeleted BIT NOT NULL DEFAULT 0
)

CREATE TABLE Flight (
	FlightId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	FlightGuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	StartDate DATETIME NOT NULL,
	GliderId INT FOREIGN KEY REFERENCES Glider (GliderId),
	TowId INT FOREIGN KEY REFERENCES Flight (FlightId),
	IgcFilename VARCHAR(255),
	AddedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IsDeleted BIT NOT NULL DEFAULT 0
)

-- One flight has many waypoints
CREATE TABLE Waypoint (
	WaypointId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	FlightId INT NOT NULL FOREIGN KEY REFERENCES Flight (FlightId),
	Latitude DECIMAL(6,4) NOT NULL,
	Longitude DECIMAL(7,4) NOT NULL,
	AltitudeMeters INT,
	[Date] DATETIME NOT NULL
)

CREATE TABLE UserRole (
	RoleId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	RoleCode CHAR(1) NOT NULL UNIQUE,
	Description VARCHAR(100) NOT NULL
)

INSERT INTO UserRole (
	RoleCode
	, Description
)
VALUES (
	'A'
	, 'Admin'
), (
	'U'
	, 'User'
);

CREATE TABLE [User] (
	UserId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	UserGuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	IdentityId VARCHAR(100),
	[Role] CHAR(1) NOT NULL FOREIGN KEY REFERENCES UserRole (RoleCode),
	Email VARCHAR(255) NOT NULL,
	AddedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IsDeleted BIT NOT NULL DEFAULT 0
)

CREATE TABLE Invitation (
	InvitationId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	UserId INT NOT NULL FOREIGN KEY REFERENCES [User] (UserId),
	Token UNIQUEIDENTIFIER NOT NULL,
	IssuedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ExpirationDate DATETIME NOT NULL
)

GO